MODEL:
  CONFIG_FILE: "configs/BallShow/vit_transreid_stride.yml"
  WEIGHT: "logs/BallShow_vit_transreid_stride/transformer_120.pth"
  DEVICE: "cuda"

DATA:
  TRAIN_DIR: "E:\\BaiduNetdiskDownload\\BallShow-ReID\\bounding_box_train"
  IMG_SIZE: [224, 224]

OUTPUT:
  FEATURES_DIR: "app_features"
  TOP_K_DEFAULT: 5
  SIMILARITY_THRESHOLD: 0.5
